# Generated by Django 4.2.11 on 2024-03-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('horario', models.DateTimeField(auto_now_add=True)),
                ('ponto', models.CharField(choices=[('E1', 'Entrada 1'), ('S1', 'Saida 1'), ('E2', 'Entrada 2'), ('S2', 'Saida 2')], max_length=2)),
                ('cpf', models.CharField(max_length=11, unique=True)),
            ],
        ),
    ]
