# Generated by Django 4.2.11 on 2024-03-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroponto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
